### ISSUE TITLE
202205319252 | Annakelly | Aba receituário | Problemas de impressão

### ISSUE THREAD

**Issue by Rebeca-oliveira713** [phelipeafonso-suporte/igut-eba-suporte#2]
Hoje a funcionária AnnaKelly e a Adrielly, entraram em contato para falar que os médicos da unidade Asa Norte não estão conseguindo imprimir receituário normal apenas o receituário especial.

https://user-images.githubusercontent.com/80768303/171176201-56445405-38e0-413f-bb57-3bbbac564d52.mp4

**Comment by phelipeafonso-suporte** [comment]
Unidade ASA NORTE está sem margens configuradas. @Rebeca-oliveira713 revisar, pega as margens da matriz e aplica igual para essa undiade.
