### ISSUE TITLE
202205309243|OTORRINO|BLOQUEIO DE INSERÇÃO DE CODIGOS NÃO EXISTENTES 

### ISSUE THREAD

**Issue by aline-nunes** [phelipeafonso-suporte/igut-eba-suporte#4]
![image](https://user-images.githubusercontent.com/69010857/171273315-6d3fe505-4ed7-4fa9-90b7-857bb98e09f3.png)

**Comment by phelipeafonso-suporte** [comment]
Mandei mensagem para entender melhor o caso. Vitor me passou sobre isso e estou solicitando explicações do cliente sobre este chamado.
Provavelmente o chamado vai mudar de nº tendo em vista que nosso git voltou
